name: CI/CD Pipeline - Node.js with Docker and AWS

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Проверка содержимого папки app
        run: ls -la app

      - name: Install Dependencies
        run: npm install
        working-directory: app

      - name: Run Tests
        run: npm test
        working-directory: app
